[package]
name = "quiz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.17", default-features = false, features = ['termion'] }
termion = "1.5"
rand = "0.8.4"
