[package]
name = "quiz"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27"
rand = "0.8.4"
ratatui = "0.25.0"
